### ISSUE TITLE
seems credentials file in ~/.aws isn't used

### ISSUE THREAD

**Issue by luck02** [motdotla/node-lambda#135] opened 2016-08-11 21:03 UTC
I could be wrong here, but I configured my credentials files, the AWS CLI works, but it looks like node-lambda stomps those with whatever's in the local environment (nothing in my case).

Is this intentional?  Am I huffing glue?

Thanks :)

**Comment by DeviaVir** [comment] 2016-09-02 08:50
@luck02 I'm unable to reproduce this. I'm using `node-lambda` without specifying `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY` in my `.env`
We did recently add `AWS_PROFILE` ([code](https://github.com/motdotla/node-lambda/commit/c315f32b540cd5cce35bcc2d09a53de186b0b26c)) support, which may be what you're running into here.

To be sure, did you set both `~/.aws/credentials` and `~/.aws/config`?

Closing until I can reproduce this case.

**Closed by DeviaVir** 2016-09-02 08:50 UTC
Labels: bug, question

**Comment by luck02** [comment] 2016-09-02 14:36
Both configs were set, however we've moved on so no longer have the setup to test.  Can't help at this point.
