### ISSUE TITLE
making node-lambda work with windows, a few suggestions and my fork

### ISSUE THREAD

**Issue by teebu** [motdotla/node-lambda#124] opened 2016-07-03 04:55 UTC
I've been trying to fix things as I'm making the latest version work with windows by using `cpr` instead of `rsync`, and `7z` instead of `zip`. I couldn't get the node-zip module to work on windows. I came across a few suggestion/issues.

1. allow 'node_modules' in prebuild directory deployment.
2. updating function code is missing the set Runtime param.

Suggestion, use less `mkdir -p`, `exec('rm -rf ')`, etc, linux commands, and use module like `fs-extra` that use `fs.emptyDir()`  to make it friendlier with other OSs. I didn't try, but fs-extra also has a fs.copy() function which is like cpr.

My changes/fixes to make it work for windows here:
https://github.com/teebu/node-lambda/commits/windows-0.8

**Comment by DeviaVir** [comment] 2016-07-12 15:53
Duplicate of #114, closing this one to make sure we have all resources in one place

**Closed by DeviaVir** 2016-07-12 15:53 UTC

**Comment by seoker** [comment] 2017-05-04 14:51
resolved by 2ee586f9c056f7052e77f773ab5ecb1a07d01faf
